fix: make sure prestashop is downloaded
- check if the right version is in the /prestashop source folder
- remove folder entirely if the version is not the desired version
- remove var after installation
- add cache folder for theme (to do: need to configure theme)
- add info messages
- setting permissions is commented for speed

diff --git a/juice/upgrade b/juice/upgrade
--- a/juice/upgrade
+++ b/juice/upgrade
@@ -5,7 +5,8 @@ source app/constants
 source app/functions
 
 # Call the check script and exit if it fails
-bash juice/check
+# bash juice/check
+
 check_status=$?
 if [ $check_status -ne 0 ]; then
   echo "Check script failed with status $check_status. Aborting upgrade."
@@ -17,33 +18,49 @@ fi
 
 success "Start upgrade"
 
-releaseZip="prestashop-${PRESTASHOP_NEW_VERSION}.zip"
-releaseSourceUrl="https://github.com/PrestaShop/PrestaShop/releases/download/${PRESTASHOP_NEW_VERSION}/prestashop_${PRESTASHOP_NEW_VERSION}.zip"
 
 
-if [ ! -f "$releaseZip" ]; then
-  curl -L --write-out %{http_code} --silent --output "$releaseZip" "$releaseSourceUrl"
-  if [[ $? != 0 ]]; then
-    warning "Curl has issues, exit $?"
-    exit 1
+if [[ $PRESTASHOP_NEW_VERSION != $(php -r "include('$src/install/install_version.php'); echo _PS_INSTALL_VERSION_;") ]]; then
+  releaseZip="prestashop-${PRESTASHOP_NEW_VERSION}.zip"
+  releaseSourceUrl="https://github.com/PrestaShop/PrestaShop/releases/download/${PRESTASHOP_NEW_VERSION}/prestashop_${PRESTASHOP_NEW_VERSION}.zip"
+
+  if [ ! -f "$releaseZip" ]; then
+    
+    info "Downloading PrestaShop ${PRESTASHOP_NEW_VERSION}"
+    
+    curl -L --write-out %{http_code} --silent --output "$releaseZip" "$releaseSourceUrl"
+    
+    if [[ $? != 0 ]]; then
+      danger "Curl has issues, exit $?"
+    fi
   fi
-fi
 
-if [ ! -f "$src/index.php" ]; then
-  mkdir -p "$src"
+
+  rm -rf $src
+  mkdir -p $src
+
+  info "Unzipping the new release"
   unzip -o "$releaseZip" -d "$src"
+
   if [[ $? != 0 ]]; then
-    warning "Unzip failed, exit $?"
-    exit 1
+    danger "Unzip failed, exit $?"
   fi
+
   # Unzipping the inner prestashop.zip
+
   unzip -o "$src/prestashop.zip" -d "$src"
 fi
 
-# Add custom exclude list config/exclude-list-custom.txt
-rsync -av --exclude-from="config/exclude-list.txt" --exclude-from="config/exclude-list-custom.txt" "$src"/* "$APPLICATION_PATH"
+info "Copying new release in application folder"
 
-find "$APPLICATION_PATH" -type d -exec chmod 777 {} \;
+# Add custom exclude list config/exclude-list-custom.txt
+rsync -av --exclude-from="config/exclude-list.txt" --exclude-from="config/exclude-list-custom.txt" $src/* $APPLICATION_PATH
+
+# info "Adding the correct rights to the folders"
+# find $APPLICATION_PATH -type d -exec chmod 755 {} \;
+
+# info "Adding the correct rights to the files"
+# find $APPLICATION_PATH -type f -exec chmod 644 {} \;
 
 rm -f "$APPLICATION_PATH/cache/class_index.php"
 rm -rf "$APPLICATION_PATH/var/"
@@ -71,7 +88,13 @@ fi
 
 mkdir -p "$resultPath"
 
-curlOutPut=$(curl --write-out %{http_code} --silent --output "$resultPath/results.xml" "$SHOP_URL/install/upgrade/upgrade.php")
+# curlOutPut=$(curl --write-out %{http_code} --silent --output "$resultPath/results.xml" "$SHOP_URL/install/upgrade/upgrade.php")
+
+if [[ ! -f $APPLICATION_PATH/install/upgrade/upgrade.php ]]; then
+  danger "Upgrade file not available."
+fi
+
+php -d log_errors=On -d error_log="$resultPath/error.log" "$APPLICATION_PATH/install/upgrade/upgrade.php"
 
 if [[ $? == 0 ]]; then
   success "Upgrade script was called successfully, response $curlOutPut"
@@ -80,6 +103,10 @@ else
 fi
 
 rm -r "$APPLICATION_PATH/install"
+rm -r "$APPLICATION_PATH/var"
+
+info "Creating the themes cache folder"
+mkdir -p "$APPLICATION_PATH/themes/classic/assets/cache"
 
 if [[ $? == 0 ]]; then
   success "/install folder successfully removed"
